name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - numpy
  - matplotlib
  - scipy
  - obspy
  - pip:
    - jupyterlite-core==0.1.0
    - jupyterlite-xeus-python==0.7.0
